# Change these first
owner: gsa
repo: ai-experience-sharing-upptime

sites:
  - name: AI Portfolio
    url: https://strapi-api-host-prod.app.cloud.gov
  - name: AI Portfolio Alert Test
    url: https://strapi-api-host-staging.app.cloud.gov


assignees:
  - taylor-work

status-website:
  baseUrl: /ai-experience-sharing-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AI Portfolio Status
  introTitle: AI Portfolio Status
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
